{% set version = "1.6.4" %}

package:
    name: fiona
    version: {{ version }}

source:
    fn: fiona-{{ version }}.post1.tar.gz
    url: https://github.com/Toblerity/Fiona/archive/{{ version }}.tar.gz
    sha256: a84fb516e69c218a5346b3850f3f5df5bd0c8fb861dc76cc05bb4ef909be7120

build:
    number: 1
    preserve_egg_dir: True
    entry_points:
        - fio=fiona.fio.main:main_group

requirements:
    build:
        - python
        - cython
        - setuptools
        - numpy x.x
        - gdal 1.11.4
    run:
        - python
        - setuptools
        - numpy x.x
        - gdal 1.11.4
        - cligj
        - munch
        - click-plugins
        - six

test:
    imports:
        - fiona
        - fiona.fio
    commands:
        - fio --help
        - conda inspect linkages fiona --name _test  # [linux]
    requires:
        - nose
    files:
        - test.cpg
        - test.dbf
        - test.shp
        - test.shx

about:
    home: http://github.com/Toblerity/Fiona
    license: BSD 3-Clause
    summary: Fiona reads and writes spatial data files

extra:
    recipe-maintainers:
        - ocefpaf
