{% set name = "fiona" %}
{% set version = "1.10.1" %}
{% set gdal_version = "3.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: b00ae357669460c6491caba29c2022ff0acfcbde86a95361ea8ff5cd14a86b68
    patches:
      - patches/0001-build-log-level.patch
  - url: https://raw.githubusercontent.com/Toblerity/Fiona/{{ version }}/fiona/_vendor/munch/LICENSE.txt
    sha256: 57ca95c92059c8380625192462979bd32994aae3fcdf902ff6eb1e467eeb0469
    folder: fiona/_vendor/munch/

build:
  number: 0
  # There is no libgdal for s390x
  skip: True  # [py<38 or s390x]
  entry_points:
    - fio = fiona.fio.main:main_group
  script_env:                                                              # [unix]
    - GDAL_VERSION={{ gdal_version }}                                      # [unix]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - cython >=3.0.2,<3.1
    - libgdal {{ gdal_version }}
    - wheel
    - setuptools >=67.8
  run:
    - python
    - attrs >=19.2.0
    - certifi
    - click >=8.0,<9.a0
    - click-plugins >=1.0
    - cligj >=0.5
    - importlib-metadata  # [py<310]
    - gdal
    # option calc
    - shapely
    - pyparsing
    # vendored:
    # snuggs 1.4.7 modified, do not unvendor
    # munch 2.5.0 probably modified, check, in case unvendor
  run_constrained:
    # option s3
    - boto3 >=1.3.1

test:
  source_files:
    - tests
  requires:
    - pytest >=7
    - boto3 >=1.3.1
    - pytz
    - pip
    - fsspec
    - aiohttp
  files:
    - test_data

about:
  home: https://github.com/Toblerity/Fiona
  license: BSD-3-Clause AND MIT
  license_file: 
    - LICENSE.txt
    - fiona/_vendor/munch/LICENSE.txt
  license_family: BSD
  summary: Fiona reads and writes spatial data files
  description: |
    Fiona reads and writes geographic data files and
    thereby helps Python programmers integrate geographic
    information systems with other computer systems.
    Fiona contains extension modules that link the
    Geospatial Data Abstraction Library (GDAL).
  doc_url: https://fiona.readthedocs.io
  dev_url: https://github.com/Toblerity/Fiona

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
