{% set version = "1.8.22" %}

package:
  name: fiona
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Fiona/Fiona-{{ version }}.tar.gz
  sha256: a82a99ce9b3e7825740157c45c9fb2259d4e92f0a886aaac25f0db40ffe1eea3

build:
  number: 0
  skip: True  # [win and vc<14]
  skip: True  # [py<36]
  # There is no libgdal for s390x
  skip: True  # [linux and s390x]
  entry_points:
    - fio = fiona.fio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.29.29
    - numpy
    - libgdal
    - wheel
    - setuptools
    - certifi  # [py<=37]
  run:
    - python
    - gdal
    - {{ pin_compatible('numpy') }}
    - attrs >=17
    - click >=4.0
    - cligj >=0.5
    - click-plugins >=1.0
    - six >=1.7
    - munch
    - shapely  # only option calc we include by default
    - certifi  # [py<=37]


test:
  source_files:
    - tests
  imports:
    - fiona
    - fiona.fio
  requires:
    - pytest >=3
    - boto3 >=1.2.4
    - packaging
    #- pytest-catchlog
    - pytz
    - pip
  files:
    - test_data
  commands:
    - pip check
    - fio --help
    - fio ls test_data/test.shp
    - fio info test_data/test.shp

about:
  home: https://github.com/Toblerity/Fiona
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Fiona reads and writes spatial data files
  doc_url: https://fiona.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
