{% set name = "fiona" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Fiona-{{ version }}.tar.gz
  sha256: 3a3725e94840a387fef48726d60db6a6791563f366939d22378a4661f8941be7

build:
  number: 0
  # There is no libgdal for s390x
  skip: True  # [py<37 or s390x]
  entry_points:
    - fio = fiona.fio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython 0.29.33
    - numpy {{ numpy }}
    - libgdal 3.6.2
    - wheel
    - setuptools
  run:
    - python
    - attrs >=19.2.0
    - certifi
    - click >=8.0,<9.dev0
    - click-plugins >=1.0
    - cligj >=0.5
    - munch >=2.3.2
    - setuptools
    - gdal
    - {{ pin_compatible('numpy') }}
    - shapely  # only option calc we include by default

test:
  source_files:
    - tests
  requires:
    - pytest >=7
    - boto3 >=1.3.1
    - pytz
    - pip
  files:
    - test_data

about:
  home: https://github.com/Toblerity/Fiona
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Fiona reads and writes spatial data files
  description: |
    Fiona reads and writes geographic data files and
    thereby helps Python programmers integrate geographic
    information systems with other computer systems.
    Fiona contains extension modules that link the
    Geospatial Data Abstraction Library (GDAL).
  doc_url: https://fiona.readthedocs.io/en/latest/
  dev_url: https://github.com/Toblerity/Fiona

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
