travis:
  secure:
    BINSTAR_TOKEN: ZmcS2gCEnSwHgHyiOa73+8terApbKiTiEZC1y8pgqcVFbdseyJAKPaHrvW1+qV0SeHUGNh81jva1RSA7INS/tirIvOr/W+AsHIYj5O6focGzxuPETfsxX6OfqrPkGg4I8guMwey/QMPQHTEuV90kLZyfBXKz7jh9diJwRlWNnvIwo70W0Z7tQq/HkefmI0qY9IoidXlfObsXRI1rJB1SN6RJoLrvCcAR2olyM+pWIF0xKMyKhxpmnk9hTBzxegFQ5GT5ZFPTDw6c9L+HfUGKK3AVG/P2dQo/w3ISFp/fajuqTzexegDP+v/wHHcSpoz0lL2M73GkENrauNKf3IKtpagpHkVAsIp0Se7RwwfUB7ZkPALw9YS6f9c30IC+jRuPf2rIFkhKD9toN7btgSg4OCyIufS9o4YOjXBXTNXRTrIlgMo/dMAN4ysVjgMdeyZNV7HrQPzAbMG15kDyRMN/DntrqGMlj3jr41UG4a17YsRFX3NSh/6QIaeGa/kR+Z2zJSgOmnetdePqT34og4YShgWW3i/edtbr3WXLYDGJeCP9yWzdQvNcBLnyMKDQlCA7rk1HXq6wFRd7PRGF6nItNOVeyzIoPsHOEaepx2Zt05SCIM7UCY3hmrhc9+JI5tVjeRCmKEewEeF/2vE0nBAMfCoyaTwLrJJAKDYehh+JF0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
